name: portfolio-optimization
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas==2.2.3
    - numpy==1.26.4
    - scikit-learn==1.6.1
    - matplotlib==3.10.0
    - seaborn==0.12.2
    - mlflow==2.18.0